// Available AI models for player selection
// Pricing tier 1-5 based on combined input/output cost (1=cheapest, 5=most expensive)
export const AI_MODELS = [
  {
    id: "openai/gpt-5-nano",
    name: "GPT-5 Nano",
    provider: "OpenAI",
    input: 0.05,
    output: 0.4,
    tier: 1,
  },
  {
    id: "openai/gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "OpenAI",
    input: 0.25,
    output: 2.0,
    tier: 2,
  },
  {
    id: "openai/gpt-5.1-codex-mini",
    name: "GPT-5.1 Codex Mini",
    provider: "OpenAI",
    input: 0.25,
    output: 2.0,
    tier: 2,
  },
  {
    id: "openai/gpt-5",
    name: "GPT-5",
    provider: "OpenAI",
    input: 1.25,
    output: 10.0,
    tier: 4,
  },
  {
    id: "openai/gpt-5.1-thinking",
    name: "GPT-5.1 Thinking",
    provider: "OpenAI",
    input: 1.25,
    output: 10.0,
    tier: 4,
  },
  {
    id: "anthropic/claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    input: 0.25,
    output: 1.25,
    tier: 1,
  },
  {
    id: "anthropic/claude-sonnet-4.5",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    input: 3,
    output: 15,
    tier: 5,
  },
  {
    id: "anthropic/claude-opus-4.5",
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    input: 5,
    output: 25,
    tier: 5,
  },
  {
    id: "xai/grok-4.1-fast-non-reasoning",
    name: "Grok 4.1 Fast",
    provider: "xAI",
    input: 0.2,
    output: 0.5,
    tier: 1,
  },
  {
    id: "xai/grok-4.1-fast-reasoning",
    name: "Grok 4.1 Fast Reasoning",
    provider: "xAI",
    input: 0.2,
    output: 0.5,
    tier: 1,
  },
  {
    id: "xai/grok-4-fast-reasoning",
    name: "Grok 4 Fast Reasoning",
    provider: "xAI",
    input: 0.2,
    output: 0.5,
    tier: 1,
  },
  {
    id: "xai/grok-3-mini",
    name: "Grok 3 Mini",
    provider: "xAI",
    input: 0.3,
    output: 0.5,
    tier: 1,
  },
  {
    id: "xai/grok-4",
    name: "Grok 4",
    provider: "xAI",
    input: 3,
    output: 15,
    tier: 5,
  },
  {
    id: "xai/grok-code-fast-1",
    name: "Grok Code Fast 1",
    provider: "xAI",
    input: 0.2,
    output: 1.5,
    tier: 2,
  },
  {
    id: "google/gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    provider: "Google",
    input: 2,
    output: 12,
    tier: 4,
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    input: 1.25,
    output: 10,
    tier: 4,
  },
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    input: 0.3,
    output: 2.5,
    tier: 2,
  },
  {
    id: "deepseek/deepseek-v3.2-exp-thinking",
    name: "DeepSeek V3.2 Thinking",
    provider: "DeepSeek",
    input: 0.28,
    output: 0.42,
    tier: 1,
  },
  {
    id: "deepseek/deepseek-v3.2-exp",
    name: "DeepSeek V3.2 Exp",
    provider: "DeepSeek",
    input: 0.27,
    output: 0.4,
    tier: 1,
  },
  {
    id: "moonshotai/kimi-k2-turbo",
    name: "Kimi K2 Turbo",
    provider: "MoonshotAI",
    input: 2.4,
    output: 10,
    tier: 4,
  },
  {
    id: "arcee-ai/trinity-mini",
    name: "Trinity Mini",
    provider: "Arcee AI",
    input: 0.04,
    output: 0.15,
    tier: 1,
  },
  {
    id: "mistral/mistral-large-3",
    name: "Mistral Large 3",
    provider: "Mistral",
    input: 0.5,
    output: 1.5,
    tier: 2,
  },
] as const;

export type AIModel = (typeof AI_MODELS)[number];
